general.import = [
  # uncomment the flavour you want below:
  # "~/dotfiles/.config/alacritty/catppuccin-latte.toml"
  "~/dotfiles/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

# [terminal.shell]
# program = "wsl"

[window]
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = true
padding = { x = 10, y = 10 }
dynamic_padding = false
dimensions = { columns = 265, lines = 80}

[env]
TERM = "xterm-256color"

############################################
#################### FONT ##################
############################################
[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font]
size = 15

